const status = {
  SUCCESS: 200,
  CREATED: 201,
  ERROR: 500,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  CONFLICT: 409,
  FORBIDDEN: 403,
  NOTFOUND: 404,
}

const MSG = {
  en: {
    notFound: 'Not Found',
    notAuthorized: 'Path not authorized',
    dataNotFound: 'Data Not Found',
    somethingWentWrong: 'Something went wrong',
    NoSelection: 'No Sub-operation Selected',
    alreadyExists: 'Already Exists',
    missingRequiredData: 'Missing required data',
    successfulLogin: 'Login successfully',
    allEmployeeAlreadyExists: 'All Employees from this list Already Exists',
    notExists: 'Your account not Exists!',
    mailNotUpdated: 'Your email is not updated, please contact to HR Team',
    invalidCredentials: 'Invalid credentials',
    invalidId: 'Invalid ID',
    invalidEmail: 'Invalid E-mail',
    invalidMobileNo: 'Invalid Mobile no.',
    invalidData: 'Invalid data.',
    invalidDateTime: 'Invalid date and time',
    dataCreated: 'Data created',
    accountPending: 'Your Request is in pending state, please verify your account and try again',
    accountInActive: 'Your Request is in InActive state, kindly wait until Admin Activate your account',
    accountBlocked:
      'Your have entered wrong password too many times and your account is blocked, Reset your password to activate your account',
    unauthorizedAccess: 'Your are not authorized to login, please don\'t try to log in again',
    operationFailed: 'Operation Failed',
    branchExists: 'Branch already Exists',
    branchNotExists: 'Branch Not Exists',
    companyExists: 'Company already Exists',
    deviceExists: 'Device already Exists',
    deviceNotExists: 'Device Not Exists',
    leaveTypeExist: 'Leave Type already Exists',
    leaveTypeNotExist: 'Leave Type Not Exists',
    departmentExists: 'Department already Exists',
    departmentNotExists: 'Department Not Exists',
    productExists: 'Product already Exists',
    productNotExists: 'Product Not Exists',
    roleExists: 'Role already Exists',
    roleNotExists: 'Role not Exists',
    permissionExists: 'Permission already Exists',
    permissionNotExists: 'Permission not Exists',
    registeredSuccessfully: 'Registered successfully',
    addedSuccessfully: 'Added successfully',
    loginSuccessfully: 'Login successfully',
    foundSuccessfully: 'Data Found Successfully',
    updatedSuccessfully: 'Updated Successfully',
    uploadedSuccessfully: 'Uploaded Successfully',
    syncedSuccessfully: 'Synced Successfully',
    syncedFailed: 'Syncing Failed',
    deletedSuccessfully: 'Deleted Successfully',
    alreadyDeleted: 'Already deleted',
    releasedLockSuccessfully: 'Lock Released Successfully',
    releasedMultipleLockSuccessfully: 'Multiple Locks Released Successfully',
    invalidOTP: 'Invalid OTP',
    otpLimitExceeded: 'The OTP limit has been exceeded',
    otpSended: 'OTP sended',
    otpExpired: 'OTP expired',
    passwordUpdated: 'Password updated',
    sequelizeError: 'Sequelize Error',
    accountNotActive: 'Your account is not active',
    usernameAlreadyUsed: 'Username is already used.',
    userExist: 'User data is already used.',
    invalidOtp: 'Invalid otp',
    accountedActivated: 'Account activation completed.',
    accountAlreadyActive: 'Account is already Active.',
    verificationSuccess: 'Successfully verified.',
    packageNotExist: 'Package not exist',
  },
}

const CRON_TIMES = {
  TODAY_NOTIFICATION: '0 0 10 * * *',
  EXCEPTIONAL_REPORT: '0 0 4 * * *',
  BIRTHDAY_NOTIFICATION_TO_TEAM: '0 10 10 * * *',
  OVERTIME_ADDITION_MISSED: '0 15 10 * * *',
  BIRTHDAY_NOTIFICATION_TO_SELF: '0 20 10 * * *',
  OVERTIME_ADDITION_MISSED_WEEK: '0 25 10 * * *',
  OVERTIME_ADDITION: '0 0 11 * * *',
  FETCH_ATTENDANCE: '0 45 23 * * *',
  SATURDAY_BENEFIT_COUNT: '0 0 1 1 * *',
}

const s3Folders = {
  category: 'Categories',
  service: 'Services',
  event: 'Events',
  banner: 'Banner',
  blog: 'Blogs',
  package: 'Packages',
  appDemo: 'AppDemo',
  salesProduct: 'Sales',
  rentalProduct: 'Rentals',
  vendor: 'Vendors',
}

const constants = {
  admin: {
    name: 'admin',
    email: 'admin@eventneedz.com',
  },
  confirmEmails: {
    from: ' "Admin | EventNeedz" <no-reply@eventneedz.com',
  },
}

module.exports = {
  status,
  MSG,
  CRON_TIMES,
  s3Folders,
  constants,
}
